### ISSUE TITLE
Floating button doesn't work in safari

### ISSUE THREAD

**Issue by yzhang-eightfold** [EightfoldAI/octuple#340]
It become an oval when floating is enabled.
![image](https://user-images.githubusercontent.com/60897218/188033292-6304d9f8-ac45-4ac7-a0f8-6b34f06b7316.png)

after investigation I noticed that it's `position: fixed` and `min-height: max-content` that cause the problem, but I wasn't able to find a solution. When these 2 attributes are set, the height of the button becomes bigger than what it's supposed to be.

Any suggestions on how it can be fixed?

**Comment by dkilgore-eightfold** [comment]
@yzhang-eightfold in the case of floating button, as it's icon only you may override the width and height to align with the button sizes beginning [line 136 of button.module.scss](https://github.com/EightfoldAI/octuple/blob/main/src/components/Button/button.module.scss#L136):

```
    &.floating {
        position: fixed;
        bottom: 40px;
        right: 40px;
        z-index: $z-index-400;
    }

    &-large {
        height: 44px;
        padding: $button-padding-vertical-large $button-padding-horizontal-large;
        
        &.floating {
            width: 44px;
            height: 44px;
        }
    }

    &-medium {
        height: 36px;
        padding: $button-padding-vertical-medium
            $button-padding-horizontal-medium;
        &.floating {
            width: 36px;
            height: 36px;
        }
    }

    &-small {
        height: 28px;
        padding: $button-padding-vertical-small $button-padding-horizontal-small;

        &.floating {
            width: 28px;
            height: 28px;
        }
    }
```

**Comment by dkilgore-eightfold** [comment]
@yzhang-eightfold PR of fix is out --> https://github.com/EightfoldAI/octuple/pull/377

**Comment by dkilgore-eightfold** [comment]
Fix merged pending release.
