### ISSUE TITLE
Table shows two scroll bars

### ISSUE THREAD

**Issue by areddy-eightfold** [EightfoldAI/octuple#352]
![image](https://user-images.githubusercontent.com/84381377/189151638-25879fa8-6e5d-425e-a219-935632aaddb8.png)

**Comment by dkilgore-eightfold** [comment]
@areddy-eightfold Please provide a [codesandbox](https://codesandbox.io/) repro.

**Comment by dkilgore-eightfold** [comment]
@areddy-eightfold Will repro and debug.

**Comment by dkilgore-eightfold** [comment]
Found the root cause. Fix is out for review as part of https://github.com/EightfoldAI/octuple/pull/389

**Comment by dkilgore-eightfold** [comment]
Fix merged as part of https://github.com/EightfoldAI/octuple/pull/389
