### ISSUE TITLE
Default no data text in Table

### ISSUE THREAD

**Issue by areddy-eightfold** [EightfoldAI/octuple#374]
![image](https://user-images.githubusercontent.com/84381377/189930234-179d8b8a-d86d-417c-b23b-9f213ceb9a8f.png)
Default no data should be something different than this. If someone forgets passing the emptyText prop the default text displayed is not very relatable to the end user. Either this or we can make the prop mandatory

**Comment by dkilgore-eightfold** [comment]
Task has been scheduled for Sprint starting 09/26/22

**Comment by dkilgore-eightfold** [comment]
Change as part of https://github.com/EightfoldAI/octuple/pull/394

**Comment by dkilgore-eightfold** [comment]
Fix merged as part of https://github.com/EightfoldAI/octuple/pull/394
