### ISSUE TITLE
Select options going under modal footer

### ISSUE THREAD

**Issue by areddy-eightfold** [EightfoldAI/octuple#375]
![image](https://user-images.githubusercontent.com/84381377/189930839-94546e42-dc8d-49c3-97f0-731727c6bd6f.png)
Select options are going under the Modal footer

Codesandbox:
https://codesandbox.io/s/form-in-modal-i603vz?file=/index.js

**Comment by dkilgore-eightfold** [comment]
Use `dropdownProps` of `Select` to fix --> https://codesandbox.io/s/form-in-modal-forked-rnkttn?file=/index.js

Because `Select` is a child of `Modal` in your scenario, some extra implementation is required.

```
dropdownProps={{
    portal: true,
    dropdownStyle: {zIndex: 100000}
}}
```
