### ISSUE TITLE
The tab highlight of option in the dropdown get cut by the next option

### ISSUE THREAD

**Issue by usinghal-eightfold** [EightfoldAI/octuple#386]
<img width="237" alt="Screenshot 2022-09-22 at 1 21 56 PM" src="https://user-images.githubusercontent.com/84313406/191689465-93340efd-3161-40ec-8008-3f4dd037a59b.png">

**Comment by ychhabra-eightfold** [comment]
dropdowns in navbar are not using menu items as of now. this is not an isue in octuple.
