### ISSUE TITLE
Table component rendering all the rows when mounted

### ISSUE THREAD

**Issue by areddy-eightfold** [EightfoldAI/octuple#388]
https://codesandbox.io/s/table-multiple-rows-g896ji?file=/index.js

Table component is rendering all the given rows when mounted which is causing performance issues. If we are displaying only 5 rows in current page, ideally it should render 5 rows but currently it is rendering all thousands of rows. It is causing lagginess and UI becomes unresponsive.

**Comment by dkilgore-eightfold** [comment]
Question, can this work be done by managing the data structure passed to the table?

**Comment by dkilgore-eightfold** [comment]
On it.

**Comment by dkilgore-eightfold** [comment]
Task has been scheduled for Sprint starting 09/26/22

**Comment by dkilgore-eightfold** [comment]
Found the issue, the pagination prop of table only currently supports `pageSize` prop of `Pagination` component, will need to add `pageSizes` prop so the `usePagination` hook of Table may read from it.

**Comment by dkilgore-eightfold** [comment]
Using `pageSize` for now should fix the issue. Suggest not passing an array and only pass the value you need.

**Comment by dkilgore-eightfold** [comment]
https://codesandbox.io/s/table-multiple-rows-forked-dg6qq9?file=/index.js

**Comment by dkilgore-eightfold** [comment]
Fix merged with https://github.com/EightfoldAI/octuple/pull/393
