### ISSUE TITLE
bug with bordered prop in Table component

### ISSUE THREAD

**Issue by aryan-eightfold** [EightfoldAI/octuple#451]
when using bordered prop in Table, it fails to render one of the borders when we have a sub-grouped table as the second last column.
attaching screenshot for reference =>
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/64970674/206354180-f83d7ed9-73fa-4c66-b812-940e3e405ddd.png">

**Comment by dkilgore-eightfold** [comment]
Tracking using ticket ENG-37177

**Comment by dkilgore-eightfold** [comment]
When bordered is true, we only apply a border on 1 of 2 sides to avoid stacking borders. In the case of `th` `td` we default to left borders. Need to refine this css to handle the last child here.
