### ISSUE TITLE
Animation jank when date pickers close on date selection

### ISSUE THREAD

**Issue by jhoward-eightfold** [EightfoldAI/octuple#464]
When the date picker closes after selecting a date, there is some noticeable bounce and flashing happening in the animation

https://user-images.githubusercontent.com/106610186/207436403-20b0f036-0fd9-47cf-9d33-f052d44dd8ba.mov

**Comment by dkilgore-eightfold** [comment]
Will update the forward hide Penner curve from easeinout to easein

**Comment by dkilgore-eightfold** [comment]
Tracking with ENG-38078
