### ISSUE TITLE
export OcThemeNames from a better location

### ISSUE THREAD

**Issue by jhoward-eightfold** [EightfoldAI/octuple#493]
currently necessary to import OcThemeNames from deep:
```
import { OcThemeNames } from '@eightfold.ai/octuple/lib/components/ConfigProvider';
```

We should expose this at a more reasonable place. It should also be named singularly, as it presents only one value. OcThemeNames can be OcThemeName[]

**Comment by dkilgore-eightfold** [comment]
Tracking with ENG-39328
