### ISSUE TITLE
id prop passed to TextArea is taking dynamic values in rendered HTML

### ISSUE THREAD

**Issue by lpatel-eightfold** [EightfoldAI/octuple#496]
The `id` prop passed to TextArea component, should ideally remain unchanged in the final HTML. But instead a number gets appended to the end of the passed `id`.
The issue can be reproduced on the storybook site as well:
https://eightfoldai.github.io/octuple.github.io/?path=/story/input--text-area&args=id:myId

![Screenshot 2023-01-09 at 20 03 34](https://user-images.githubusercontent.com/85925534/211332816-be1ad474-1cd2-4af0-a1d1-dfb162419d75.png)

**Comment by dkilgore-eightfold** [comment]
@lpatel-eightfold noted, in the meantime if your goal is to use the id for test purposes, please use `data-test-id` instead. If using for css, consider using the `classNames` prop.

**Comment by dkilgore-eightfold** [comment]
Tracking with ENG-39552
