### ISSUE TITLE
border-color used for inputs is not a11y friendly

### ISSUE THREAD

**Issue by jhoward-eightfold** [EightfoldAI/octuple#498]
`--border-color: #bec2ca;`
![Screenshot 2023-01-10 at 2 03 59 PM](https://user-images.githubusercontent.com/106610186/211651177-92e93a58-1e22-45ad-908e-6a42db654f59.png)

We should use this opportunity to create a more semantic naming of this variable (--input-border-color), leaving the previous one in as-is...

**Comment by dkilgore-eightfold** [comment]
To clarify, this is relevant only for the CSS Variable. Pure Octuple components are A11y conformant.

**Comment by dkilgore-eightfold** [comment]
![inputBorder](https://user-images.githubusercontent.com/99700808/211695505-ac4eea05-3e6a-457e-9aa2-f5a1346f5852.png)

**Comment by dkilgore-eightfold** [comment]
![input](https://user-images.githubusercontent.com/99700808/211695563-dd7907d8-d26d-41b5-8b69-c8a87fecac8a.png)

**Comment by dkilgore-eightfold** [comment]
current local variables in input.module.scss

--input-border-color: var(--grey-color-60);
--input-border-color-active: var(--grey-color-80);

**Comment by dkilgore-eightfold** [comment]
Tracking with ENG-39677
