### ISSUE TITLE
Select component onOptionsChange not reacting properly

### ISSUE THREAD

**Issue by yzhang-eightfold** [EightfoldAI/octuple#562]
When `props.options[*].value` is js object, Select component onOptionsChange doesn't react properly to option clicks

sandbox:
https://codesandbox.io/s/select-forked-w7qz5b?file=/demo.js

screen recording:
https://user-images.githubusercontent.com/60897218/223909469-cff1f995-b7ad-44ee-a1ba-8364cbce532d.mov

**Comment by dkilgore-eightfold** [comment]
Tracking with ENG-46082
