### ISSUE TITLE
bodyPadding prop on Panel does not work

### ISSUE THREAD

**Issue by jhoward-eightfold** [EightfoldAI/octuple#565]
Toggling bodyPadding prop does not disable body padding IF AND ONLY IF headerPadding is disabled

<img width="1800" alt="Screenshot 2023-03-16 at 10 29 08 AM" src="https://user-images.githubusercontent.com/106610186/225666684-e0d97006-7277-4929-bc95-0f5b78b48209.png">

**Comment by dkilgore-eightfold** [comment]
Looks like a SASS bug.

https://github.com/EightfoldAI/octuple/blob/main/src/components/Panel/panel.module.scss#L113-L137

```
  &.no-body-padding {
      padding: 0;

      .header {
        padding: $space-l $space-xl $space-m $space-xl; // BUG?
      }

      .footer {
        padding: $space-m $space-xl $space-l $space-xl; // BUG?
      }
    }

    &.no-header-padding {
      padding: 0;
      .header {
        padding: 0;
      }
      .body {
        padding: 0 $space-xl; // BUG
      }
      .footer {
        padding: $space-m $space-xl $space-l $space-xl; // BUG?
      }
    }
```

**Comment by dkilgore-eightfold** [comment]
Tracking with ENG-46504
