### ISSUE TITLE
Octuple Panel is not Mobile Friendly

### ISSUE THREAD

**Issue by szhang-eightfold** [EightfoldAI/octuple#574]
https://user-images.githubusercontent.com/104794005/228086821-5df37c3c-0128-40fe-a936-d040680c8f44.mov

Whenever the panel is opened say in Iphone SE view port, the panel seems to be bigger than the screen and there is no way to zoom in/out

**Comment by dkilgore-eightfold** [comment]
@szhang-eightfold In the meantime, using a condition to show full screen modal vs panel is recommended.

**Comment by szhang-eightfold** [comment]
Hey Dylan, this is already small size in Iphone SE viewport, I see, the full screen modal suggestion is a good one, will take a look

**Comment by dkilgore-eightfold** [comment]
Great, in the meantime I'll take this feedback to UX and see about the best way to handle small screens. There is a small screen modal design, but not sure if we plan on using it for Panels.

**Comment by dkilgore-eightfold** [comment]
Tracking with ticket ENG-47622
