### ISSUE TITLE
AvatarGroup component doesn't show anything if only one item provided

### ISSUE THREAD

**Issue by jhoward-eightfold** [EightfoldAI/octuple#603]
https://github.com/EightfoldAI/octuple/blob/main/src/components/Avatar/AvatarGroup.tsx#L114

AvatarGroup is used to display manager(s), but typically there is only one to display. In this scenario, AvatarGroup shows nothing.
![Screenshot 2023-04-24 at 11 31 45 AM](https://user-images.githubusercontent.com/106610186/234059419-7634280f-cf69-440a-be55-049ec5b9b30f.png)

**Comment by karurst-eightfold** [comment]
https://github.com/EightfoldAI/octuple/pull/604
