### ISSUE TITLE
Table component loading prop is continuously loading when used

### ISSUE THREAD

**Issue by ykelkar-eightfold** [EightfoldAI/octuple#623]
![image](https://github.com/EightfoldAI/octuple/assets/102243974/efe8f4c1-976f-4470-b31e-01485e06564e)

Seems to not be checking the value of loading in the code, but checking the typeof instead:
![image](https://github.com/EightfoldAI/octuple/assets/102243974/4661103d-7cf9-46b3-95c7-3f4a7f8bbc85)

**Comment by dkilgore-eightfold** [comment]
Tracking with ENG-54186
