### ISSUE TITLE
Popup is not triggered when tabbed into it with keyboard

### ISSUE THREAD

**Issue by szhang-eightfold** [EightfoldAI/octuple#652]
In Octuple popup http://octuple.eightfold-corp.ai/?path=/story/popup--popups, if we set the trigger to be "hover", and then we try to tab into the button via keyboard, the hover is not getting triggered by the tab focus and so the popup does not show up. Ideally it should behave the same as tooltip.

**Comment by dkilgore-eightfold** [comment]
Tracking with ENG-57120
