### ISSUE TITLE
Slider bug: hideRail prop seems to do nothing

### ISSUE THREAD

**Issue by jhoward-eightfold** [EightfoldAI/octuple#653]
![Screenshot 2023-06-23 at 12 55 52 PM](https://github.com/EightfoldAI/octuple/assets/106610186/d14dfacf-fa87-4e6d-8541-f2eed6241c76)

Expecting this to hide the highlighting between values, or between left and single value, but it seems to do nothing.

![Screenshot 2023-06-23 at 12 57 11 PM](https://github.com/EightfoldAI/octuple/assets/106610186/afaf5317-44aa-4a8d-91b5-0ac170232108)

**Comment by dkilgore-eightfold** [comment]
Tracking with ENG-57121
