### ISSUE TITLE
[Popup] popup closes too soon

### ISSUE THREAD

**Issue by lpatel-eightfold** [EightfoldAI/octuple#681]
We are displaying an action button inside the button, if user tries to navigate to the button when popup appears, then the popup closes before the mouse enters the popup area. See attached screen recording:

https://github.com/EightfoldAI/octuple/assets/85925534/5f91cf3c-3937-4c59-b575-164ac1771199

Can be reproduced in ef app:
- Login as demo@eightfolddemo-sbandapalli.com
- Goto https://stage.eightfold.ai/position/pipeline_v2?pid=15511077&query_id=DRmxmRGY
- Try the steps in screen recording

**Comment by dkilgore-eightfold** [comment]
Try setting `offset` prop to `0` and `visibleArrow` to `false`

**Comment by lpatel-eightfold** [comment]
This worked perfectly. Thank You!
