### ISSUE TITLE
[Enhancement][Table] Allow collapsing/expanding individual rows

### ISSUE THREAD

**Issue by lpatel-eightfold** [EightfoldAI/octuple#683]
We have usecase where we need to display multiple project data in one row:
![Screenshot 2023-08-08 at 16 13 47](https://github.com/EightfoldAI/octuple/assets/85925534/eb1b2e4f-8f02-4f70-8fe5-b489d6bfbb1c)

If there are too many projects, the row will get very long and won't look good.
It would be ideal if we can have an expand/collapse option on each row if the height of row exceeds a certain limit.

**Comment by dkilgore-eightfold** [comment]
Table already supports this [feature](https://eightfoldai.github.io/octuple.github.io/?path=/story/table--expandable-row).
