### ISSUE TITLE
Button flashes if var is linear-gradient

### ISSUE THREAD

**Issue by jhoward-eightfold** [EightfoldAI/octuple#692]
Reproduction:
https://codesandbox.io/s/button-animation-flashing-43kc7l?file=/index.js

If css var for button hover is made a gradient, the button will flash when exiting hover state. Presuming this is an artifact of the transition, but haven't dug into it.

**Comment by dkilgore-eightfold** [comment]
background gradients have limited CSS3 transition support. For now override the button animation.

Here's an example:

https://codesandbox.io/s/button-animation-flashing-forked-qh7hmr?file=/index.css

**Comment by dkilgore-eightfold** [comment]
Tracking with ENG-62150
