### ISSUE TITLE
Octuple Link is showing undefined as tooltip on hover

### ISSUE THREAD

**Issue by sravichandran-eightfold** [EightfoldAI/octuple#700]
When hovering over a link implemented in octuple link. There is a HTMl tooltip which says undefined.
Code Reference
https://github.com/EightfoldAI/octuple/blob/main/src/components/Link/Link.tsx#L61

https://github.com/EightfoldAI/octuple/blob/main/src/components/Link/Link.tsx#L19

Can we have a default value to the octuple title prop

**Comment by dkilgore-eightfold** [comment]
@sravichandran-eightfold Is this tooltip implemented in the host? `Link` has no built-in `Tooltip`.

**Comment by dkilgore-eightfold** [comment]
@sravichandran-eightfold Assuming a default `title` should not be the solution, and as the `Link` children may be a `Node`, we cannot assume the content at this level.

**Comment by sravichandran-eightfold** [comment]
I think the problem here is the template string insert undefined when the title prop is not passed.

**Comment by dkilgore-eightfold** [comment]
The title prop should always be defined via implementation as a best practice. It's not up to the library to determine this content.
