### ISSUE TITLE
slider: with step set slider is sometimes showing rail beyond or short of value

### ISSUE THREAD

**Issue by jhoward-eightfold** [EightfoldAI/octuple#703]
<img width="1800" alt="Screenshot 2023-08-31 at 1 45 50 PM" src="https://github.com/EightfoldAI/octuple/assets/106610186/11710224-9d86-4809-9ea5-860c5495bf0f">

**Comment by dkilgore-eightfold** [comment]
Is this related to resizing the browser via web inspector toggle?
