### ISSUE TITLE
InlineSvg Optimization

### ISSUE THREAD

**Issue by szhang-eightfold** [EightfoldAI/octuple#711]
Currently InlineSvg fetch every image if given an url, so there is opportunities for repetitive fetching which is not ideal

Would be nice to Enhance it to have caching capability

Would be a plus if it can also sanitize the given svg link if not already

**Comment by dkilgore-eightfold** [comment]
@szhang-eightfold sanitizing the link should be done by the host. The component should not make the assumption to sanitize content passed from props as it could lead to duped sanitization and unintended omissions of content. We also don't want to assume any security dependency on behalf of the host.
