### ISSUE TITLE
Selected option text not updating when options are updated in Select component

### ISSUE THREAD

**Issue by sthorat-eightfold** [EightfoldAI/octuple#718]
On changing the options of the Select component, the options in the dropdown menu update but not the selected option's text.

Video for reference: https://www.loom.com/share/95b13b23e5744087bb89607653933f21?sid=9b58f644-c423-4b50-aca7-7d13f339403c

**Comment by dkilgore-eightfold** [comment]
The input browser cache needs to be cleared via the `clear` prop, then you set the selected option.
