### ISSUE TITLE
Tab does not automatically apply label value as ariaLabel

### ISSUE THREAD

**Issue by jhoward-eightfold** [EightfoldAI/octuple#723]
For consideration, tab does not automatically apply label to aria-label. This might be of particular relevance when there is badge content. If there is no badge content, then the label speaks for itself and aria label isn't really needed. 🤷 

![Screenshot 2023-10-10 at 3 35 08 PM](https://github.com/EightfoldAI/octuple/assets/106610186/72bce1e6-1058-41cc-88ec-3a47e43f8795)

**Comment by dkilgore-eightfold** [comment]
Screen reader should read the label text, if an aria label is added, won't it be read twice?

**Comment by jhoward-eightfold** [comment]
I'm not sure here. Screen readers seem to read the label combined with the badge which is perhaps expected and okay?
