### ISSUE TITLE
upload file with dropzone traps focus

### ISSUE THREAD

**Issue by jhoward-eightfold** [EightfoldAI/octuple#725]
when using octuple file upload with dropzone, when focus gets to the select file button it gets stuck there. 
The Bug is reproduced in the following sandbox instance: https://k2t32g.csb.app/

**Comment by dkilgore-eightfold** [comment]
Fix is local to the button in `Upload`, but there is a bug that needs to be addressed in `Dropzone` as the button prevents default behavior internally. Will need to add a compare for tab keycode to fix the tab loop.

```
<Upload {...uploadProps}>
  <PrimaryButton
    htmlType={"button"}
    onKeyDown={(event) => {
      if (event.keyCode !== 9) {
        event.preventDefault();
      }
    }}
    text={"Select file"}
  />
</Upload>
```

**Comment by dkilgore-eightfold** [comment]
Will be released in vNext
