### ISSUE TITLE
Panel focusTrap and autoFocus do not seem to work

### ISSUE THREAD

**Issue by jhoward-eightfold** [EightfoldAI/octuple#733]
Reproducible in `/careerhub/search/people`
When clicking on a person the profile panel opens, it does not take auto focus and does not focus trap despite these being default settings for Panel component.

**Comment by dkilgore-eightfold** [comment]
This is an implementation issue.

**Comment by dkilgore-eightfold** [comment]
Part of the problem is with useFocusTrap hook. Will fix this one so that we use an interval instead of a timeout

**Comment by dkilgore-eightfold** [comment]
The other part is there's no `footer` in the above implementation to complete the loop. Investigating why this is relevant to `FocusTrap` as there's no code requiring a footer. Most likely an async issue loading the content.
