### ISSUE TITLE
Tooltip disappears when it receives focus

### ISSUE THREAD

**Issue by dcoblentz-eightfold** [EightfoldAI/octuple#763]
When tabbing to an item that has a tooltip, we focus the item and show the tooltip. If the user presses tab again, we focus the tooltip (which allows a screen reader to read it out) but the tooltip automatically disappears.

https://github.com/EightfoldAI/octuple/assets/119535119/3bb57324-ad2f-4748-8ea5-60a6e202f506

**Comment by dkilgore-eightfold** [comment]
The element that triggers the tooltip references the tooltip element with [aria-describedby](https://w3c.github.io/aria/#aria-describedby).

**Comment by dkilgore-eightfold** [comment]
Tooltips should not be included in the tab loop.

**Comment by dkilgore-eightfold** [comment]
Tracking with ENG-74737
