### ISSUE TITLE
Consider disabling border-radius for full screen modals

### ISSUE THREAD

**Issue by jhoward-eightfold** [EightfoldAI/octuple#782]
In order to avoid the peek-a-boo corners we should consider disabling border radius on a modal in full screen mode.
<img width="923" alt="Screenshot 2024-02-09 at 1 38 04 PM" src="https://github.com/EightfoldAI/octuple/assets/106610186/1f7f2086-9576-4f23-aa23-d27b15d4e47f">

**Comment by dkilgore-eightfold** [comment]
For now, CSS vars are always at your disposal.

**Comment by jhoward-eightfold** [comment]
We will implement this. Should be a trivial change with little risk and will look much better on mobile

**Comment by jhoward-eightfold** [comment]
was actually implemented here:
https://github.com/EightfoldAI/octuple/pull/783/files#diff-d7c37afac3e46899832cd0d2b60e8659ad3db87fd0d932b947107c2cb2bf6850R47
