### ISSUE TITLE
[TwoStateButton] ButtonShape.Round not working with TwoStateButton

### ISSUE THREAD

**Issue by rkondra-eightfold** [EightfoldAI/octuple#784]
This line of code is missing in TwoStateButton https://github.com/EightfoldAI/octuple/blob/f796ff97ee5e40b39a20f670832b63f7c36fe0a8/src/components/Button/Button.tsx#L161
<img width="1039" alt="Screenshot 2024-02-13 at 9 47 23 AM" src="https://github.com/EightfoldAI/octuple/assets/96047250/aed6aa60-339a-443f-a79e-5ee2d39d0b35">

**Comment by dkilgore-eightfold** [comment]
TwoStateButton should never be used as an icon button.

**Comment by dkilgore-eightfold** [comment]
You may be considering ButtonShape.Pill?

**Comment by dkilgore-eightfold** [comment]
If it's not the shape, use a plain old Neutral toggle button.

**Comment by rkondra-eightfold** [comment]
Hi @dkilgore-eightfold  - for now using Pill shape with a border radius (from styles.round), but only TwoStateButton has the color change inbuilt, can you please point me to some example where we are doing this with Neutral toggle button (I think involves different classes to manipulate color?)

**Comment by rkondra-eightfold** [comment]
https://github.com/EightfoldAI/vscode/pull/54593#discussion_r1487150173
