### ISSUE TITLE
Accordion body color does not cover entire body

### ISSUE THREAD

**Issue by jhoward-eightfold** [EightfoldAI/octuple#817]
On the element providing the body background color for accordions, there is margin to provide gutters around the sides, but this creates strips without background color.
Forward fixed with:
```
[class*='accordion-body-container'] {
  background-color: var(--accordion-body-background-color);
}
```

![Screenshot 2024-04-16 at 11 26 28 PM](https://github.com/EightfoldAI/octuple/assets/106610186/2025e215-b10d-48e3-871d-c5a317b2fa83)

**Comment by dkilgore-eightfold** [comment]
Use the CSS variable, scoped locally for now.

e.g.

```
.my-accordion-class {
  --accordion-body-background-color: red;
  ...
}
```

**Comment by dkilgore-eightfold** [comment]
Fixed as part of https://github.com/EightfoldAI/octuple/pull/783
