### ISSUE TITLE
Accordion medium changes size when focused

### ISSUE THREAD

**Issue by jhoward-eightfold** [EightfoldAI/octuple#818]
When using medium size for Accordion, the size of the accordion button changes when keyboard focused.
https://github.com/EightfoldAI/octuple/assets/106610186/c22ff96a-aa37-473e-8887-80b7af71dd9b

**Comment by jhoward-eightfold** [comment]
does not repro. thinking this is a vscode style conflict issue
https://codesandbox.io/p/sandbox/accordion-size-change-on-focus-repro-kk9d3s?file=%2Fsrc%2FApp.js%3A21%2C22-41%2C11

**Comment by dkilgore-eightfold** [comment]
Fixed as of v2.50.1
